name: bestapp_package
description: A new Flutter package project.
version: 0.0.1
author: Steeve
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  intl: ^0.16.1
  shared_preferences: ^2.0.5
  google_maps_webservice: ^0.0.17
  flutter_google_places: ^0.2.5
  geocoder: ^0.2.1
  geolocator: ^6.1.9
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
