name: bestapp_package
description: A new Flutter package project.
version: 0.0.1
author: Steeve Bernard
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.0.3
  geocoder: ^0.2.1
  geolocator: ^7.0.3
  toast: ^0.1.5
  flash: ^1.5.2+1
  path_provider: ^2.0.1
  flutter_image_compress: ^1.0.0
  flutter_svg: ^0.22.0
  provider: ^5.0.0
  flutter_typeahead: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
